source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '9.0'
use_frameworks!

target "Exercise_JingLuo" do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'AFNetworking', '~> 3.0'
    pod 'ObjectMapper', '~> 3.1'
    pod 'Kingfisher'
    pod 'Masonry'
end

target "Exercise_JingLuoTests" do
    pod 'RxSwift'
    pod 'ObjectMapper', '~> 3.1'
end

